<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Torenzo" name="com.ghana.app.qa.testcases.PersonalInfoPageTest" tests="12" failures="0" timestamp="26 Jul 2019 07:33:35 GMT" time="50.988" errors="1">
  <testcase name="clickOnGenderTest" time="0.236" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="passMiddleNameTest" time="0.441" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="selectPassExpiryDateTest" time="4.329" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="passPlaceOfBirthTest" time="0.357" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="fillSignUpFormTest" time="35.211" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="verifyPersonalInfoTest" time="2.272" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="selectPassIssueDateTest" time="4.425" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="passFirstNameTest" time="0.322" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest">
    <error type="java.lang.AssertionError" message="First name is not matched when match with Test Data expected [Naveen] but found [Pratik]">
      <![CDATA[java.lang.AssertionError: First name is not matched when match with Test Data expected [Naveen] but found [Pratik]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.ghana.app.qa.testcases.PersonalInfoPageTest.passFirstNameTest(PersonalInfoPageTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- passFirstNameTest -->
  <testcase name="getApplicationPageTitleTest" time="2.346" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="getApplicationIdTest" time="0.267" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="passLastNameTest" time="0.397" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
  <testcase name="passPassportNumberTest" time="0.385" classname="com.ghana.app.qa.testcases.PersonalInfoPageTest"/>
</testsuite> <!-- com.ghana.app.qa.testcases.PersonalInfoPageTest -->
